graph LR

classDef root stroke-width:4px
classDef default fill:aquamarine,stroke:#009061,color:#333333

A{{AAAA}} --> B
A --> C
A --> D
C --> E
C --> D

class A root
class A default
class B default
class E default
class C default
class D default
